#####vehicle side stuff
/alpha_rise/reporter_c2_serial_comm:
  ros__parameters:
    port: /dev/ttyAMA0
    baudrate: 57600

# /alpha_rise/reporter_c2_udp_comm:
#   ros__parameters:
#     type: client
#     server_ip: 192.168.2.200
#     server_port: 5000
#     client_ip: 192.168.2.50
#     client_port: 6000
#     dccl_tx_interval: 1.0


/alpha_rise/mvp_c2_reporter:
  ros__parameters:
    dccl_tx_interval: 1.0
    helm_state_list: ['start', 'kill', 'teleop', 'survey'] #this has to match the helm
    launch_packages: ['alpha_rise_bringup', 'alpha_rise_bringup', 'alpha_rise_bringup', 'alpha_rise_bringup',  'alpha_rise_bringup', 'alpha_rise_bringup']
    launch_files: ['bringup_utilities', 'bringup_sensors', bringup_localization, 'bringup_mvp', 'bringup_thrusters', 'rosbag_record']
    gpio_devices: ['payload_24v', 'regular_payload', 'backseat']  # this needs to match the gpio manager yaml

## topside stuff
/alpha_rise/mvp_c2_commander:
  ros__parameters:
    dccl_tx_interval: 1.0
    helm_state_list: ['start', 'kill', 'teleop', 'survey'] #this has to match the helm
    launch_packages: ['alpha_rise_bringup', 'alpha_rise_bringup', 'alpha_rise_bringup', 'alpha_rise_bringup',  'alpha_rise_bringup', 'alpha_rise_bringup']
    launch_files: ['bringup_utilities', 'bringup_sensors', bringup_localization, 'bringup_mvp', 'bringup_thrusters', 'rosbag_record']
    gpio_devices: ['payload_24v', 'regular_payload', 'backseat']  # this needs to match the gpio manager yaml


# /alpha_rise/commander_c2_udp_comm:
#   ros__parameters:
#     type: server
#     server_ip: 192.168.2.200
#     server_port: 5000
#     client_ip: 192.168.2.50
#     client_port: 6000

/alpha_rise/commander_c2_serial_comm:
  ros__parameters:
    port: /dev/ttyUSB0
    baudrate: 57600
