workspace_name: "ros2_ws"

# Packages whose *config/*.yaml files that needs to be saved
package_names:
  - "alpha_rise_bringup"
  - "alpha_rise_config"

bag_output_dir: "/mnt/ssd/allen_harbor_09_22/" 
