workspace_name: "ros2_ws"

# Packages whose *config/*.yaml files that needs to be saved
package_names:
  - "alpha_rise_bringup"
  - "alpha_rise_config"

# Packages whose .urdf files need to be copied into the bag session folder
urdf_package_names:
  - "alpha_rise_description"

bag_output_dir: "/home/mvp_admin/ssd/fogo_island_05_2026"
