/alpha_rise/imu_driver_node:
    ros__parameters:
      roll_offset: 3.1415926
      pitch_offset: 0.0
      yaw_offset: 1.5707
      roll_reverse: 1.0
      pitch_reverse: -1.0
      yaw_reverse: -1.0

/alpha_rise/thruster_driver_node:
    ros__parameters:
      thruster_pub_topic: /alpha_rise/stonefish/thruster_command
      thruster_length: 4
      thruster_sub_topics: [/alpha_rise/control/thruster/surge, 
                          /alpha_rise/control/thruster/sway_bow, 
                          /alpha_rise/control/thruster/heave_stern, 
                          /alpha_rise/control/thruster/heave_bow]

/alpha_rise/dvl_driver_node:
    ros__parameters:
      dvl_in: /alpha_rise/dvl/stonefish/raw
      dvl_out: /alpha_rise/dvl/twist
      dvl_alt_out: /alpha_rise/dvl/altitude